<?php
/**
 * This file is a part of Selkie.
 *
 * Selkie is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Selkie is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Selkie. If not, see <http://www.gnu.org/licenses/>.
 *
 * @author Julien Fontanet <julien.fontanet@vates.fr>
 * @license http://www.gnu.org/licenses/gpl-3.0-standalone.html GPLv3
 *
 * @package Selkie
 */

$title = 'Rolls';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
	<a href="<?php echo $this->url('selkie', array('action'=>'add'));?>">Add new roll</a>
</p>

<p>
<form class="form" action="<?php echo $this->url('selkie', array('action' => 'search')); ?>" method="post">
<input name="id" type="text" value=""> <input type="submit" value="View voucher">
</form>
</p>

<table class="table table-condensed table-bordered table-striped">
<tr>
	<th>Identifier</th>
	<th>Creator</th>
	<th>Duration</th>
	<th>Creation</th>
	<th>Activation</th>
	<th>Comment</th>
	<th>&nbsp;</th>
</tr>
<?php foreach ($rolls as $roll): ?>
<tr>
	<td><a href="<?php echo $this->url('selkie', array('action'=>'view', 'id' => $roll->id));?>"><?php echo $this->escapeHtml($roll->pfs_id);?></a></td>
	<td><?php echo $this->escapeHtml($roll->creator);?></td>
	<td><?php echo $this->escapeHtml($roll->duration);?> minutes</td>
	<td><?php echo $this->escapeHtml($roll->creation);?></td>
	<td><?php echo ($roll->activation === null ? '<em>not activated</em>' : $this->escapeHtml($roll->activation));?></td>
	<td><?php echo ($this->escapeHtml($roll->comment) ?: '<em>none</em>');?></td>
	<td>
		<?php if ($this->isAdmin) { ?>
		<a href="<?php echo $this->url('selkie',
			array('action'=>'delete', 'id' => $roll->id));?>">Delete</a>
		<?php } else { ?>&nbsp;<?php } ?>
	</td>
</tr>
<?php endforeach; ?>
</table>
