<?php
/**
 * This file is a part of Selkie.
 *
 * Selkie is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Selkie is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Selkie. If not, see <http://www.gnu.org/licenses/>.
 *
 * @author Julien Fontanet <julien.fontanet@vates.fr>
 * @license http://www.gnu.org/licenses/gpl-3.0-standalone.html GPLv3
 *
 * @package Selkie
 */

$title = 'Batchs';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
	<a href="<?php echo $this->url('selkie', array('action'=>'add'));?>">Add new batch</a>
</p>

<table class="table">
<tr>
	<th>Creator</th>
	<th>Duration</th>
	<th>Creation</th>
	<th>Activation</th>
	<th>Comment</th>
	<th>&nbsp;</th>
</tr>
<?php foreach ($batchs as $batch): ?>
<tr>
	<td><?php echo $this->escapeHtml($batch->creator);?></td>
	<td><?php echo $this->escapeHtml($batch->duration);?></td>
	<td><?php echo $this->escapeHtml($batch->creation);?></td>
	<td><?php echo $this->escapeHtml($batch->activation);?></td>
	<td><?php echo $this->escapeHtml($batch->comment);?></td>
	<td>
		<a href="<?php echo $this->url('selkie',
			array('action'=>'print', 'id' => $batch->id));?>">Print</a>
		<?php if ($this->isAdmin) { ?>
		<a href="<?php echo $this->url('selkie',
			array('action'=>'delete', 'id' => $batch->id));?>">Delete</a>
		<?php } ?>
	</td>
</tr>
<?php endforeach; ?>
</table>
