<?php
/**
 * This file is a part of Selkie.
 *
 * Selkie is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Selkie is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Selkie. If not, see <http://www.gnu.org/licenses/>.
 *
 * @author Julien Fontanet <julien.fontanet@vates.fr>
 * @license http://www.gnu.org/licenses/gpl-3.0-standalone.html GPLv3
 *
 * @package Selkie
 */

$title = 'View roll '.$this->roll->pfs_id;
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p class="pull-left">
	<a href="<?php echo $this->url('selkie'); ?>">
		<i class="icon-arrow-left"></i> Rolls list
	</a>
</p>
<?php if ($this->isAdmin) { ?>
<p class="pull-right">
	<a href="<?php echo $this->url('selkie', array('action'=>'delete', 'id' => $roll->id));?>">
		<i class="icon-remove"></i> Delete
	</a>
</p>
<?php } ?>
<table class="table table-striped">
<tr>
	<th>Identifier</th>
	<td><?php echo $this->escapeHtml($roll->pfs_id);?></td>
</tr>
<tr>
	<th>Creator</th>
	<td><?php echo $this->escapeHtml($roll->creator);?></td>
</tr>
<tr>
	<th>Duration</th>
	<td><?php echo $this->escapeHtml($roll->duration);?> minutes</td>
</tr>
<tr>
	<th>Creation</th>
	<td><?php echo $this->escapeHtml($roll->creation);?></td>
</tr>
<tr>
	<th>Activation</th>
	<td><?php echo ($roll->activation === null ? '<em>not activated</em>' : $this->escapeHtml($roll->activation));?></td>
</tr>
<tr>
	<th>Comment</th>
	<td><?php echo ($this->escapeHtml($roll->comment) ?: '<em>none</em>');?></td>
</tr>
<tr>
	<th>Voucher<?php if (count($vouchers) > 1) echo 's ('.count($vouchers).')';?></th>
	<td>
		<?php foreach ($vouchers as $voucher): ?>
		<div>
			<a href="<?php echo $this->url('selkie', array('action'=>'print', 'id' => $voucher->id));?>"<?php if ($voucher['printed']) {?> class="muted"<?php }?> title="Print this voucher."><i class="icon-print"></i> <?php echo $this->escapeHtml($voucher->id); ?></a>
		</div>
		<?php endforeach; ?>
	</td>
</tr>
</table>
